#[theme]
#primaryColor="#3872fb"
#backgroundColor="#0e1117"
#secondaryBackgroundColor="#cece1b"
#textColor="#fafafa"
#font="sans serif"

[theme]
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"

